from .config import (
    BASE_URL,
    START_URL,
    NUM_ARTICLES,

    CHUNK_SIZE,
    CHUNK_OVERLAP,

    OPENAI_API_KEY,
    TEXT_EMBEDDING_MODEL,
    IMAGE_EMBEDDING_MODEL,
    CHAT_MODEL,
    TEMPERATURE_STRICT,
    TEMPERATURE_CREATIVE,
    TOP_K,
)
from .paths import (
    RAW_JSON,
    PROCESSED_JSON,
    RAW_IMAGES_DIR,
    PROCESSED_IMAGES_DIR,
    TEXT_EMBEDDINGS_PATH,
    IMAGE_EMBEDDINGS_PATH,
    TEXT_INDEX_PATH,
    IMAGE_INDEX_PATH,
    UNIFIED_METADATA_PATH,
    QUERY_EXPANSION_PATH,
)
from .rag_prompt import RAG_PROMPT
from .system_prompt import SYSTEM_PROMPT
from .generate_queries_prompt import GENERATE_QUERIES_PROMPT
